/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#20201f',
        tertiary: '#edefff',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed': '#1a1c1c',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#4e4800',
        'on-primary-container': '#645c00',
        'secondary-container': '#454747',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#b4b5b5',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#003ea8',
        'on-error': '#690005',
        'on-surface-variant': '#cdc7ab',
        background: '#131313',
        'secondary-fixed': '#e2e2e2',
        'on-tertiary-container': '#0050d3',
        'surface-dim': '#131313',
        'tertiary-container': '#c6d2ff',
        surface: '#131313',
        'secondary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#002a78',
        'primary-fixed-dim': '#dac900',
        'inverse-primary': '#686000',
        'on-secondary': '#2f3131',
        'surface-container-low': '#1c1b1b',
        'surface-variant': '#353535',
        'primary-container': '#e8d600',
        'inverse-surface': '#e5e2e1',
        'surface-tint': '#dac900',
        'outline-variant': '#4a4732',
        secondary: '#c6c6c7',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed': '#00174b',
        'on-background': '#e5e2e1',
        'surface-container-highest': '#353535',
        'on-secondary-fixed-variant': '#454747',
        error: '#ffb4ab',
        'surface-bright': '#393939',
        'tertiary-fixed': '#dbe1ff',
        outline: '#969178',
        'surface-container-lowest': '#0e0e0e',
        'primary-fixed': '#f8e522',
        'on-primary': '#363100',
        'on-surface': '#e5e2e1',
        primary: '#fff28a',
        'on-primary-fixed': '#1f1c00',
        'status-red': '#DC2626',
        'status-green': '#16A34A',
        'status-amber': '#D97706',
        'status-blue': '#2563EB',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        'panel-padding': '24px',
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        'margin-desktop': '32px',
        unit: '4px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'metric-sm': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'metric-lg': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'metric-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'metric-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
